version: "3.9"

services:
  spark-master:
    build:
      context: .
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./dist:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  spark-console:
    build:
      context: .
    volumes:
      - ./dist:/opt/spark-apps
      - ./data:/opt/spark-data
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKLOAD=submit
    
  spark-worker:
    build:
      context: .
    deploy:
      replicas: 3
    ports:
      - "8080"
      - "7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker
    volumes:
      - ./dist:/opt/spark-apps
      - ./data:/opt/spark-data
